### ISSUE TITLE
Difficulty in comparing Zmatrices

### ISSUE THREAD

**Issue by RaphaelRobidas** [mcocdawc/chemcoord#73]
#### Code Sample, a copy-pastable example if possible

```python
import chemcoord as cc
import pandas as pd

si = cc.Cartesian.read_xyz('test1.xyz', start_index=1)
sf = cc.Cartesian.read_xyz('test2.xyz', start_index=1)

z1 = si.get_zmat()
c_table = z1.loc[:, ['b', 'a', 'd']]
z2 = sf.get_zmat(c_table)

dz = z1 - z2
```
#### Problem description

At the last line of the above code, I get many warnings that dummy atoms were added (e.g. 5 for ethane), and it crashes for any sort of large-ish molecule with errors like the following:
```
Traceback (most recent call last):
  File "/home/raphael/.local/lib/python3.9/site-packages/chemcoord/internal_coordinates/_zmat_class_core.py", line 563, in _insert_dummy_zmat
    zmat._metadata['last_valid_cartesian'] = zmat.get_cartesian()
  File "/home/raphael/.local/lib/python3.9/site-packages/chemcoord/internal_coordinates/_zmat_class_core.py", line 656, in get_cartesian
    raise InvalidReference(i=i, b=b, a=a, d=d,
chemcoord.exceptions.InvalidReference: Atom 16 uses an invalid/linear reference spanned by: {'b': 15, 'a': 12, 'd': 34}
```
It surprises me than a tiny molecule like ethane required dummy atoms, since I just rotated a methyl group on the structure. Calculating `z1 + z2` works and does not yield any warning nor error. Even loading twice the same structure and substracting the Zmatrices results in this sort of crash.

Here are two pairs of .xyz files which have this issue, namely ethane (test1.xyz and test2.xyz) and a larger molecule which causes a crash (test3.xyz and test4.xyz).

[test_files.zip](https://github.com/mcocdawc/chemcoord/files/8083826/test_files.zip)

#### Expected Output

I would expect the subtraction to yield the differences in internal coordinate without error. The use of so many dummy atoms seems odd to me, but maybe they are actually necessary?

If this issue is intrinsic to Zmatrices, is there a way to retry the generation of the Zmatrices with different reference points? I just want to compare the differences between the two structures, even if it takes several attempts at the Zmatrix generation. 

#### Output of ``cc.show_versions()``

<details>
INSTALLED VERSIONS
------------------
python: 3.9.2.final.0
python-bits: 64
OS: Linux
OS-release: 5.10.0-10-amd64
machine: x86_64
processor: 
LC_ALL: None
LANG: en_CA.UTF-8
LOCALE: en_CA.UTF-8

chemcoord: 2.0.5
numpy: 1.21.5
scipy: 1.7.3
pandas: 1.3.4
numba: 0.55.1
sortedcontainers: 2.4.0
sympy: 1.9
pytest: 6.2.5
pip: 21.3.1
setuptools: 52.0.0
IPython: 7.20.0
sphinx: 4.3.1
</details>

**Comment by mcocdawc** [comment]
Hello,

> If this issue is intrinsic to Zmatrices

This is exactly the point. The resulting z-matrix of the operation
```
z1 - z2
```
is usually not a valid Z-matrix. Since my code tries to preserve validity upon every change it tries to cure this Z-matrix.

This can lead to undesired behaviour in the case of assignments and operators.
For assignments there are the `unsafe_(i)loc` methods to explicitly say that you perform an assignment where you know that the result might be invalid. They are described in the tutorial [here](https://nbviewer.org/github/mcocdawc/chemcoord/blob/v2.0.5/Tutorial/Zmat.ipynb#Assignments).

For the operators there is unfortunately only one `-` symbol. Here there is  a contextmanager to switch of the test for validity for the operators. You find it in the documentation [here](https://chemcoord.readthedocs.io/en/v2.0.5/src_zmat_functions/chemcoord.zmat_functions.TestOperators.html#chemcoord.zmat_functions.TestOperators), it also appears in the tutorial [here](https://nbviewer.org/github/mcocdawc/chemcoord/blob/v2.0.5/Tutorial/Zmat.ipynb#Movements-without-small-angular-approximation).

All in all the correct code for interpolation is:

```python3
with cc.TestOperators(False):
    steps = [(z2 - z1).minimize_dihedral()  * i / N for i in range(N + 1)]

# The result of z1 + step should be again a valid Z-matrix.
[z1 + step for step in steps]
```
